<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="14434" started-at="2019-09-26T15:55:24Z" finished-at="2019-09-26T15:55:39Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="14434" started-at="2019-09-26T15:55:24Z" finished-at="2019-09-26T15:55:39Z">
      <class name="pk1.Mavenpro2.Demo1">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:pk1.Mavenpro2.Demo1@88ff2c]" name="beforeTest" is-config="true" duration-ms="9737" started-at="2019-09-26T22:55:24Z" finished-at="2019-09-26T22:55:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testEasy()[pri:0, instance:pk1.Mavenpro2.Demo1@88ff2c]" name="testEasy" duration-ms="2087" started-at="2019-09-26T22:55:34Z" finished-at="2019-09-26T22:55:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEasy -->
        <test-method status="FAIL" signature="testEasy2()[pri:0, instance:pk1.Mavenpro2.Demo1@88ff2c]" name="testEasy2" duration-ms="33" started-at="2019-09-26T22:55:36Z" finished-at="2019-09-26T22:55:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pk1.Mavenpro2.Demo1.testEasy2(Demo1.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEasy2 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:pk1.Mavenpro2.Demo1@88ff2c]" name="afterTest" is-config="true" duration-ms="2538" started-at="2019-09-26T22:55:36Z" finished-at="2019-09-26T22:55:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- pk1.Mavenpro2.Demo1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
